language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t happyleader/imposc-ui -f ./imposc-ui/Dockerfile.dev ./imposc-ui
  - docker build -t happyleader/imposc-cpp -f ./imposc-service/imposc-cpp/Dockerfile.dev ./imposc-service/imposc-cpp
  - docker build -t happyleader/imposc-service -f ./imposc-service/Dockerfile ./imposc-service

script:
  - docker run -e CI=true happyleader/imposc-ui npm run test -- --coverage
  - docker run -e CI=true happyleader/imposc-cpp ./build/test/Test

after_success:
    - docker build -t happyleader/imposc-service ./imposc-service
    - docker build -t happyleader/imposc-ui ./imposc-ui
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push happyleader/imposc-service
    - docker push happyleader/imposc-ui

# deploy:
#     provider: elasticbeanstalk
#     region: "eu-west-2"
#     app: "impact-oscillator"
#     env: "Impactoscillator-env"
#     bucket-name: "elasticbeanstalk-eu-west-2-500699635973"
#     bucket-path: "impact-oscillator"
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY


# # deploy:
#     provider: lambda
#     function_name: imposcpy # Name of the Lambda being created or updated
#     edge: true # opt in to dpl v2
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY
#     memory_size: 512 # default is 128
#     runtime: python3.8
#     zip: ./imposc-service/imposcpy
#     region: eu-west-2
#     role: "$IMPOSCPY_IAM_ROLE"
#     module_name: imposc
