language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t happyleader/imposc-ui -f Dockerfile.dev ./imposc-ui

script:
  - docker run -e CI=true happyleader/imposc-ui npm run test -- --coverage