# See https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/docker-multicontainer-migration.html

version: "3.8"
services:
  service:
    stdin_open: true
    build:
      context: ./imposc-service
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    mem_limit: 256m
  ui:
    stdin_open: true
    build:
      context: ./imposc-ui
      dockerfile: Dockerfile
      args:
        - REACT_APP_IMPOSC_URL=service
        - REACT_APP_IMPOSC_PORT=4000
    ports:
      - 80:3000
    volumes:
      - /app/node_modules
      - ./imposc-ui:/app
    depends_on:
      - service
    links:
      - service
    mem_limit: 256m
