version: '3'
services:
  service:
    stdin_open: true
    build:
      context: ./imposc-service
      dockerfile: Dockerfile
    ports:
      - 5000:5000
  ui:
    stdin_open: true
    build:
      context: ./imposc-ui
      dockerfile: Dockerfile
      args:
        - REACT_APP_IMPOSC_URL= ${REACT_APP_IMPOSC_URL}
        - REACT_APP_IMPOSC_PORT= ${REACT_APP_IMPOSC_PORT}
    ports:
      - 80:80
    volumes:
      - /app/node_modules
      - ./imposc-ui:/app
    depends_on:
      - service
  test-ui:
    stdin_open: true
    build:
      context: ./imposc-ui
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./imposc-ui:/app
    command: ["npm", "run", "test"]  
  test-cpp:
    stdin_open: true
    build:
      context: ./imposc-service/imposc-cpp
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/proj/imposc-cpp/build
      - ./imposc-service/imposc-cpp:/usr/src/proj/imposc-cpp
    command: ["./build/test/Test"]
  test-service:
    stdin_open: true
    build:
      context: ./imposc-service
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/proj/imposc-cpp/build
      - ./imposc-service:/usr/src/proj
    command: ["python","-m","pytest"]
  