# See https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/docker-multicontainer-migration.html

version: '2.4'
services:
  service:
    stdin_open: true
    build:
      context: ./imposc-service
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    mem_limit: 256m
  ui:
    stdin_open: true
    build:
      context: ./imposc-ui
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - /app/node_modules
      - ./imposc-ui:/app
    environment:
      - REACT_APP_IMPOSC_URL=http://0.0.0.0
      - REACT_APP_IMPOSC_PORT=5000
    depends_on:
      - service
    links:
      - service
    mem_limit: 256m
    env_file:
      - .env
