version: '3'
services:
  ui:
    stdin_open: true
    build:
      context: ./imposc-ui
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./imposc-ui:/app
  test-ui:
    stdin_open: true
    build:
      context: ./imposc-ui
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./imposc-ui:/app
    command: ["npm", "run", "test"]  
  test-cpp:
    stdin_open: true
    build:
      context: ./imposc-cpp
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/proj/build
      - ./imposc-cpp:/usr/src/proj
    command: ["./build/test/Test"]
  