version: '3'
services:
  web:
    stdin_open: true
    build:
      context: ./imposc-ui
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./imposc-ui:/app
  tests:
    stdin_open: true
    build:
      context: ./imposc-ui
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./imposc-ui:/app
    command: ["npm", "run", "test"]