name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build UI test image
      run: docker build -t happyleader/imposc-ui -f ./imposc-ui/Dockerfile.dev ./imposc-ui
    - name: Build Cpp test image
      run: docker build -t happyleader/imposc-cpp -f ./imposc-service/imposc-cpp/Dockerfile.dev ./imposc-service/imposc-cpp
    - name: Test UI image
      run: docker run -e CI=true happyleader/imposc-ui npm run test -- --coverage
    - name: Test Cpp image
      run: docker run -e CI=true happyleader/imposc-cpp ./build/test/Test

    - name: Log into DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for UI
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: happyleader/imposc-ui
          
    - name: Build and push UI Docker image
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./imposc-ui
        push: true 
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Extract metadata (tags, labels) for service
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: happyleader/imposc-service
        
    - name: Build and push service Docker image
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./imposc-service
        push: true 
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
